// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/coupon/issue.proto

package couponconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	coupon "github.com/loveo2d/CouponIssuanceSystem/internal/api/proto/coupon"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IssueCouponServiceName is the fully-qualified name of the IssueCouponService service.
	IssueCouponServiceName = "rpc_coupon.IssueCouponService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IssueCouponServiceIssueCouponProcedure is the fully-qualified name of the IssueCouponService's
	// IssueCoupon RPC.
	IssueCouponServiceIssueCouponProcedure = "/rpc_coupon.IssueCouponService/IssueCoupon"
)

// IssueCouponServiceClient is a client for the rpc_coupon.IssueCouponService service.
type IssueCouponServiceClient interface {
	IssueCoupon(context.Context, *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error)
}

// NewIssueCouponServiceClient constructs a client for the rpc_coupon.IssueCouponService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIssueCouponServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IssueCouponServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	issueCouponServiceMethods := coupon.File_proto_coupon_issue_proto.Services().ByName("IssueCouponService").Methods()
	return &issueCouponServiceClient{
		issueCoupon: connect.NewClient[coupon.IssueCouponRequest, coupon.IssueCouponResponse](
			httpClient,
			baseURL+IssueCouponServiceIssueCouponProcedure,
			connect.WithSchema(issueCouponServiceMethods.ByName("IssueCoupon")),
			connect.WithClientOptions(opts...),
		),
	}
}

// issueCouponServiceClient implements IssueCouponServiceClient.
type issueCouponServiceClient struct {
	issueCoupon *connect.Client[coupon.IssueCouponRequest, coupon.IssueCouponResponse]
}

// IssueCoupon calls rpc_coupon.IssueCouponService.IssueCoupon.
func (c *issueCouponServiceClient) IssueCoupon(ctx context.Context, req *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error) {
	return c.issueCoupon.CallUnary(ctx, req)
}

// IssueCouponServiceHandler is an implementation of the rpc_coupon.IssueCouponService service.
type IssueCouponServiceHandler interface {
	IssueCoupon(context.Context, *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error)
}

// NewIssueCouponServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIssueCouponServiceHandler(svc IssueCouponServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	issueCouponServiceMethods := coupon.File_proto_coupon_issue_proto.Services().ByName("IssueCouponService").Methods()
	issueCouponServiceIssueCouponHandler := connect.NewUnaryHandler(
		IssueCouponServiceIssueCouponProcedure,
		svc.IssueCoupon,
		connect.WithSchema(issueCouponServiceMethods.ByName("IssueCoupon")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc_coupon.IssueCouponService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IssueCouponServiceIssueCouponProcedure:
			issueCouponServiceIssueCouponHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIssueCouponServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIssueCouponServiceHandler struct{}

func (UnimplementedIssueCouponServiceHandler) IssueCoupon(context.Context, *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc_coupon.IssueCouponService.IssueCoupon is not implemented"))
}
