// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/coupon/service.proto

package couponconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	coupon "github.com/loveo2d/CouponIssuanceSystem/internal/api/proto/coupon"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CouponServiceName is the fully-qualified name of the CouponService service.
	CouponServiceName = "rpc_coupon.CouponService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CouponServiceIssueCouponProcedure is the fully-qualified name of the CouponService's IssueCoupon
	// RPC.
	CouponServiceIssueCouponProcedure = "/rpc_coupon.CouponService/IssueCoupon"
)

// CouponServiceClient is a client for the rpc_coupon.CouponService service.
type CouponServiceClient interface {
	IssueCoupon(context.Context, *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error)
}

// NewCouponServiceClient constructs a client for the rpc_coupon.CouponService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCouponServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CouponServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	couponServiceMethods := coupon.File_proto_coupon_service_proto.Services().ByName("CouponService").Methods()
	return &couponServiceClient{
		issueCoupon: connect.NewClient[coupon.IssueCouponRequest, coupon.IssueCouponResponse](
			httpClient,
			baseURL+CouponServiceIssueCouponProcedure,
			connect.WithSchema(couponServiceMethods.ByName("IssueCoupon")),
			connect.WithClientOptions(opts...),
		),
	}
}

// couponServiceClient implements CouponServiceClient.
type couponServiceClient struct {
	issueCoupon *connect.Client[coupon.IssueCouponRequest, coupon.IssueCouponResponse]
}

// IssueCoupon calls rpc_coupon.CouponService.IssueCoupon.
func (c *couponServiceClient) IssueCoupon(ctx context.Context, req *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error) {
	return c.issueCoupon.CallUnary(ctx, req)
}

// CouponServiceHandler is an implementation of the rpc_coupon.CouponService service.
type CouponServiceHandler interface {
	IssueCoupon(context.Context, *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error)
}

// NewCouponServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCouponServiceHandler(svc CouponServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	couponServiceMethods := coupon.File_proto_coupon_service_proto.Services().ByName("CouponService").Methods()
	couponServiceIssueCouponHandler := connect.NewUnaryHandler(
		CouponServiceIssueCouponProcedure,
		svc.IssueCoupon,
		connect.WithSchema(couponServiceMethods.ByName("IssueCoupon")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc_coupon.CouponService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CouponServiceIssueCouponProcedure:
			couponServiceIssueCouponHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCouponServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCouponServiceHandler struct{}

func (UnimplementedCouponServiceHandler) IssueCoupon(context.Context, *connect.Request[coupon.IssueCouponRequest]) (*connect.Response[coupon.IssueCouponResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc_coupon.CouponService.IssueCoupon is not implemented"))
}
