// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/campaign/service.proto

package campaign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_campaign_service_proto protoreflect.FileDescriptor

const file_proto_campaign_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/campaign/service.proto\x12\frpc_campaign\x1a\x1bproto/campaign/create.proto\x1a\x18proto/campaign/get.proto2\xc2\x01\n" +
	"\x0fCampaignService\x12[\n" +
	"\x0eCreateCampaign\x12#.rpc_campaign.CreateCampaignRequest\x1a$.rpc_campaign.CreateCampaignResponse\x12R\n" +
	"\vGetCampaign\x12 .rpc_campaign.GetCampaignRequest\x1a!.rpc_campaign.GetCampaignResponseBEZCgithub.com/loveo2d/CouponIssuanceSystem/internal/api/proto/campaignb\x06proto3"

var file_proto_campaign_service_proto_goTypes = []any{
	(*CreateCampaignRequest)(nil),  // 0: rpc_campaign.CreateCampaignRequest
	(*GetCampaignRequest)(nil),     // 1: rpc_campaign.GetCampaignRequest
	(*CreateCampaignResponse)(nil), // 2: rpc_campaign.CreateCampaignResponse
	(*GetCampaignResponse)(nil),    // 3: rpc_campaign.GetCampaignResponse
}
var file_proto_campaign_service_proto_depIdxs = []int32{
	0, // 0: rpc_campaign.CampaignService.CreateCampaign:input_type -> rpc_campaign.CreateCampaignRequest
	1, // 1: rpc_campaign.CampaignService.GetCampaign:input_type -> rpc_campaign.GetCampaignRequest
	2, // 2: rpc_campaign.CampaignService.CreateCampaign:output_type -> rpc_campaign.CreateCampaignResponse
	3, // 3: rpc_campaign.CampaignService.GetCampaign:output_type -> rpc_campaign.GetCampaignResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_campaign_service_proto_init() }
func file_proto_campaign_service_proto_init() {
	if File_proto_campaign_service_proto != nil {
		return
	}
	file_proto_campaign_create_proto_init()
	file_proto_campaign_get_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_campaign_service_proto_rawDesc), len(file_proto_campaign_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_campaign_service_proto_goTypes,
		DependencyIndexes: file_proto_campaign_service_proto_depIdxs,
	}.Build()
	File_proto_campaign_service_proto = out.File
	file_proto_campaign_service_proto_goTypes = nil
	file_proto_campaign_service_proto_depIdxs = nil
}
