// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/coupon/issue.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int32                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponRequest) Reset() {
	*x = IssueCouponRequest{}
	mi := &file_proto_coupon_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponRequest) ProtoMessage() {}

func (x *IssueCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coupon_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponRequest.ProtoReflect.Descriptor instead.
func (*IssueCouponRequest) Descriptor() ([]byte, []int) {
	return file_proto_coupon_issue_proto_rawDescGZIP(), []int{0}
}

func (x *IssueCouponRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type IssueCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	CampaignId    int32                  `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,3,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponResponse) Reset() {
	*x = IssueCouponResponse{}
	mi := &file_proto_coupon_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponResponse) ProtoMessage() {}

func (x *IssueCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coupon_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponResponse.ProtoReflect.Descriptor instead.
func (*IssueCouponResponse) Descriptor() ([]byte, []int) {
	return file_proto_coupon_issue_proto_rawDescGZIP(), []int{1}
}

func (x *IssueCouponResponse) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *IssueCouponResponse) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *IssueCouponResponse) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *IssueCouponResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

var File_proto_coupon_issue_proto protoreflect.FileDescriptor

const file_proto_coupon_issue_proto_rawDesc = "" +
	"\n" +
	"\x18proto/coupon/issue.proto\x12\n" +
	"rpc_coupon\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x12IssueCouponRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x05R\n" +
	"campaignId\"\xad\x01\n" +
	"\x13IssueCouponResponse\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\x05R\n" +
	"campaignId\x12\x1f\n" +
	"\vcoupon_code\x18\x03 \x01(\tR\n" +
	"couponCode\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt2f\n" +
	"\x12IssueCouponService\x12P\n" +
	"\vIssueCoupon\x12\x1e.rpc_coupon.IssueCouponRequest\x1a\x1f.rpc_coupon.IssueCouponResponse\"\x00BCZAgithub.com/loveo2d/CouponIssuanceSystem/internal/api/proto/couponb\x06proto3"

var (
	file_proto_coupon_issue_proto_rawDescOnce sync.Once
	file_proto_coupon_issue_proto_rawDescData []byte
)

func file_proto_coupon_issue_proto_rawDescGZIP() []byte {
	file_proto_coupon_issue_proto_rawDescOnce.Do(func() {
		file_proto_coupon_issue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coupon_issue_proto_rawDesc), len(file_proto_coupon_issue_proto_rawDesc)))
	})
	return file_proto_coupon_issue_proto_rawDescData
}

var file_proto_coupon_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_coupon_issue_proto_goTypes = []any{
	(*IssueCouponRequest)(nil),    // 0: rpc_coupon.IssueCouponRequest
	(*IssueCouponResponse)(nil),   // 1: rpc_coupon.IssueCouponResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_coupon_issue_proto_depIdxs = []int32{
	2, // 0: rpc_coupon.IssueCouponResponse.issued_at:type_name -> google.protobuf.Timestamp
	0, // 1: rpc_coupon.IssueCouponService.IssueCoupon:input_type -> rpc_coupon.IssueCouponRequest
	1, // 2: rpc_coupon.IssueCouponService.IssueCoupon:output_type -> rpc_coupon.IssueCouponResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_coupon_issue_proto_init() }
func file_proto_coupon_issue_proto_init() {
	if File_proto_coupon_issue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coupon_issue_proto_rawDesc), len(file_proto_coupon_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coupon_issue_proto_goTypes,
		DependencyIndexes: file_proto_coupon_issue_proto_depIdxs,
		MessageInfos:      file_proto_coupon_issue_proto_msgTypes,
	}.Build()
	File_proto_coupon_issue_proto = out.File
	file_proto_coupon_issue_proto_goTypes = nil
	file_proto_coupon_issue_proto_depIdxs = nil
}
