// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/coupon/service.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_coupon_service_proto protoreflect.FileDescriptor

const file_proto_coupon_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/coupon/service.proto\x12\n" +
	"rpc_coupon\x1a\x18proto/coupon/issue.proto2_\n" +
	"\rCouponService\x12N\n" +
	"\vIssueCoupon\x12\x1e.rpc_coupon.IssueCouponRequest\x1a\x1f.rpc_coupon.IssueCouponResponseBCZAgithub.com/loveo2d/CouponIssuanceSystem/internal/api/proto/couponb\x06proto3"

var file_proto_coupon_service_proto_goTypes = []any{
	(*IssueCouponRequest)(nil),  // 0: rpc_coupon.IssueCouponRequest
	(*IssueCouponResponse)(nil), // 1: rpc_coupon.IssueCouponResponse
}
var file_proto_coupon_service_proto_depIdxs = []int32{
	0, // 0: rpc_coupon.CouponService.IssueCoupon:input_type -> rpc_coupon.IssueCouponRequest
	1, // 1: rpc_coupon.CouponService.IssueCoupon:output_type -> rpc_coupon.IssueCouponResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coupon_service_proto_init() }
func file_proto_coupon_service_proto_init() {
	if File_proto_coupon_service_proto != nil {
		return
	}
	file_proto_coupon_issue_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coupon_service_proto_rawDesc), len(file_proto_coupon_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coupon_service_proto_goTypes,
		DependencyIndexes: file_proto_coupon_service_proto_depIdxs,
	}.Build()
	File_proto_coupon_service_proto = out.File
	file_proto_coupon_service_proto_goTypes = nil
	file_proto_coupon_service_proto_depIdxs = nil
}
